import { useEffect, useMemo, useState } from 'react'
import {
  ArrowRight, ArrowUpRight, BarChart3, Check, ChevronRight, CircleHelp,
  Clock3, CreditCard, History as HistoryIcon, LayoutDashboard, LoaderCircle,
  LockKeyhole, Menu, MessageSquareText, MoreHorizontal, RefreshCw, ShieldCheck,
  Sparkles, Target, TimerReset, TriangleAlert, X, Zap,
} from 'lucide-react'
import './App.css'

type View = 'overview' | 'execution' | 'history'
type Recovery = {
  event_id: string; timestamp: string; subscription_id: string; payment_id: string
  amount_due: number; currency: string; failed_type: string
  customer?: { name?: string; email?: string; preferred_channel?: string; plan_name?: string }
  recovery_score?: number; baseline_probability?: number; recommended_action?: string
  chosen_action?: string; agent_reasoning?: string; rescue_link_url?: string
  retry_delay_hours?: number; recovered_amount?: number; action_history?: Array<{ execution_status?: string; gateway_or_provider_response?: Record<string, unknown> }>
  status?: string
}
type Scenario = { id: string; customer: string; email: string; plan: string; amount: number; failedType: string; errorCode: string; retry: number; channel: string; initials: string; tone: 'red' | 'orange' | 'blue'; tenureDays: number; successfulPayments: number; description: string }
const API_URL = import.meta.env.VITE_API_URL || 'http://127.0.0.1:8000'
const scenarios: Scenario[] = [
  { id: 'evt_live_01', customer: 'Arjun Mehta', email: 'arjun@example.com', plan: 'Pro Monthly', amount: 4999, failedType: 'expired_card', errorCode: 'EXPIRED_CARD', retry: 1, channel: 'whatsapp', initials: 'AM', tone: 'red', tenureDays: 120, successfulPayments: 4, description: 'Card expired. Customer intent remains strong.' },
  { id: 'evt_live_02', customer: 'Priya Sharma', email: 'priya@example.com', plan: 'Starter Tier', amount: 499, failedType: 'network_error', errorCode: 'GATEWAY_ERROR', retry: 1, channel: 'email', initials: 'PS', tone: 'blue', tenureDays: 40, successfulPayments: 1, description: 'Transient gateway error. Retry quietly when the switch clears.' },
  { id: 'evt_live_03', customer: 'Enterprise Client X', email: 'billing@enterprisex.com', plan: 'Enterprise Annual', amount: 65000, failedType: 'card_declined', errorCode: 'DO_NOT_HONOR', retry: 3, channel: 'email', initials: 'EX', tone: 'orange', tenureDays: 400, successfulPayments: 14, description: 'High-value account at risk after a late retry attempt.' },
  { id: 'evt_live_04', customer: 'Nisha Kapoor', email: 'nisha@example.com', plan: 'Growth Annual', amount: 12999, failedType: 'insufficient_funds', errorCode: 'INSUFFICIENT_FUNDS', retry: 1, channel: 'email', initials: 'NK', tone: 'orange', tenureDays: 210, successfulPayments: 9, description: 'Balance is low. Give the customer time and a clear recovery path.' },
  { id: 'evt_live_05', customer: 'Rohan Das', email: 'rohan@example.com', plan: 'Pro Monthly', amount: 2999, failedType: 'incorrect_cvc', errorCode: 'INVALID_CVC', retry: 2, channel: 'whatsapp', initials: 'RD', tone: 'red', tenureDays: 75, successfulPayments: 6, description: 'CVC mismatch. A payment link can resolve this without a retry loop.' },
  { id: 'evt_live_06', customer: 'Meera Iyer', email: 'meera@example.com', plan: 'Team Monthly', amount: 8999, failedType: 'timeout', errorCode: 'NETWORK_TIMEOUT', retry: 2, channel: 'email', initials: 'MI', tone: 'blue', tenureDays: 185, successfulPayments: 12, description: 'Gateway timed out. Let the infrastructure recover before messaging.' },
  { id: 'evt_live_07', customer: 'Kabir Singh', email: 'kabir@example.com', plan: 'Business Monthly', amount: 21999, failedType: 'processing_error', errorCode: 'BANK_SYSTEM_OUTAGE', retry: 1, channel: 'email', initials: 'KS', tone: 'blue', tenureDays: 95, successfulPayments: 5, description: 'Issuer processing issue. A short retry window is the least disruptive move.' },
  { id: 'evt_live_08', customer: 'Aarav Malhotra', email: 'aarav@example.com', plan: 'Premium Annual', amount: 24999, failedType: 'fraudulent', errorCode: 'FRAUD', retry: 1, channel: 'email', initials: 'AM', tone: 'red', tenureDays: 60, successfulPayments: 2, description: 'Risk signal detected. The agent should stop automated recovery and review.' },
]
const money = (value = 0) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value)
const timeAgo = (timestamp?: string) => { if (!timestamp) return 'Just now'; const minutes = Math.max(1, Math.round((Date.now() - new Date(timestamp).getTime()) / 60000)); return minutes < 60 ? `${minutes}m ago` : `${Math.round(minutes / 60)}h ago` }

function App() {
  const [started, setStarted] = useState(false), [view, setView] = useState<View>('overview')
  const [history, setHistory] = useState<Recovery[]>([]), [executions, setExecutions] = useState<Recovery[]>([])
  const [activeScenario, setActiveScenario] = useState<string | null>(null), [loadingHistory, setLoadingHistory] = useState(false)
  const [notice, setNotice] = useState(''), [menuOpen, setMenuOpen] = useState(false)
  const fetchHistory = async () => { setLoadingHistory(true); try { const response = await fetch(`${API_URL}/api/recoveries?limit=50`); if (!response.ok) throw new Error(); const data = await response.json(); setHistory(data.events || []) } catch { setNotice('History is temporarily unavailable. The agent can still run simulations.') } finally { setLoadingHistory(false) } }
  useEffect(() => { if (started) fetchHistory() }, [started])
  const runAgent = async (scenario: Scenario) => { setActiveScenario(scenario.id); setNotice(''); try { const response = await fetch(`${API_URL}/api/test/simulate-failure`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ plan_name: scenario.plan, amount_due: scenario.amount, failed_type: scenario.failedType, raw_error_code: scenario.errorCode, current_retry_count: scenario.retry, customer_name: scenario.customer, customer_email: scenario.email, customer_phone: '+919876543210', preferred_channel: scenario.channel, tenure_days: scenario.tenureDays, successful_payments: scenario.successfulPayments }) }); if (!response.ok) throw new Error(); const result = await response.json(); setExecutions((current) => [result.data, ...current]); setHistory((current) => [result.data, ...current]); setView('execution') } catch { setNotice('Could not reach the recovery agent. Check that the backend is running on port 8000.') } finally { setActiveScenario(null) } }
  const metrics = useMemo(() => ({ failed: history.length, recovered: history.filter((item) => item.status === 'RECOVERED').length, amount: history.filter((item) => item.status === 'RECOVERED').reduce((total, item) => total + (item.recovered_amount ?? item.amount_due ?? 0), 0) }), [history])
  if (!started) return <Landing onStart={() => setStarted(true)} />
  return <main className="app-shell"><header className="topbar"><button className="brand" onClick={() => setStarted(false)} aria-label="Go to home"><span className="brand-mark">r</span><span>recovery<span className="brand-dot">.</span></span></button><div className="topbar-right"><span className="live-pill"><span className="pulse" /> Agent live</span><span className="merchant-label">Acme Cloud, Inc.</span><button className="avatar">AC</button><button className="icon-button mobile-menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu"><Menu size={18} /></button></div></header><div className={`workspace ${menuOpen ? 'menu-visible' : ''}`}><aside className="sidebar"><div className="workspace-title"><div className="eyebrow">Recovery command center</div><h1>Good morning, Acme</h1><p>Protect revenue before it slips away.</p></div><nav className="nav-tabs" aria-label="Dashboard sections"><TabButton icon={<LayoutDashboard size={17} />} label="Live payments" active={view === 'overview'} onClick={() => setView('overview')} badge={scenarios.length} /><TabButton icon={<Zap size={17} />} label="Execution" active={view === 'execution'} onClick={() => setView('execution')} badge={executions.length} /><TabButton icon={<HistoryIcon size={17} />} label="History" active={view === 'history'} onClick={() => setView('history')} /></nav><div className="sidebar-foot"><div className="secure-note"><LockKeyhole size={15} /><span>Razorpay test environment</span></div><button className="help-link"><CircleHelp size={15} /> Help center <ArrowUpRight size={13} /></button></div></aside><section className="content-area"><div className="content-head"><div><div className="breadcrumb">Payments <ChevronRight size={14} /> Recovery</div><h2>{view === 'overview' ? 'Live payments' : view === 'execution' ? 'Agent execution' : 'Recovery history'}</h2></div><div className="head-actions"><span className="last-updated"><span className="status-dot" /> Updated just now</span><button className="outline-button" onClick={fetchHistory} disabled={loadingHistory}><RefreshCw size={15} className={loadingHistory ? 'spin' : ''} /> Refresh</button></div></div>{notice && <div className="notice"><TriangleAlert size={16} /> {notice} <button onClick={() => setNotice('')} aria-label="Dismiss"><X size={15} /></button></div>}<KpiStrip metrics={metrics} />{view === 'overview' && <Overview scenarios={scenarios} onRun={runAgent} activeScenario={activeScenario} history={history} />}{view === 'execution' && <Execution executions={executions} />}{view === 'history' && <HistoryView history={history} loading={loadingHistory} />}</section></div></main>
}

function Landing({ onStart }: { onStart: () => void }) { return <main className="landing"><header className="landing-nav"><button className="brand"><span className="brand-mark">r</span><span>recovery<span className="brand-dot">.</span></span></button><span className="landing-status"><span className="pulse" /> Built for recurring payments</span></header><section className="landing-hero"><div className="hero-copy"><div className="hero-kicker"><Sparkles size={15} /> Revenue recovery, on autopilot</div><h1>Turn failed payments into <em>another chance.</em></h1><p>One clear command center for every failed charge, every agent decision, and every recovered rupee.</p><button className="primary-button large" onClick={onStart}>Open command center <ArrowRight size={18} /></button><div className="hero-proof"><span><ShieldCheck size={15} /> Policy-led actions</span><span><Zap size={15} /> Real-time decisions</span></div></div><div className="hero-visual"><div className="visual-grid" /><div className="recovery-orbit"><div className="orbit-line" /><div className="orbit-core"><span>₹</span><small>RECOVERED</small></div><div className="orbit-card card-one"><span className="mini-icon blue"><RefreshCw size={13} /></span><div><b>Retry scheduled</b><small>Network error · 4h</small></div><Check size={15} className="success-icon" /></div><div className="orbit-card card-two"><span className="mini-icon green"><Check size={13} /></span><div><b>Payment rescued</b><small>Pro Monthly · ₹4,999</small></div><ArrowUpRight size={15} className="success-icon" /></div><div className="orbit-card card-three"><span className="mini-icon orange"><Target size={13} /></span><div><b>Agent reasoning</b><small>Highest expected ROI</small></div></div></div></div></section><footer className="landing-footer"><span>RECOVERY AGENT <b>01</b></span><span>Operational clarity for modern merchants <ArrowUpRight size={13} /></span></footer></main> }
function TabButton({ icon, label, active, onClick, badge }: { icon: React.ReactNode; label: string; active: boolean; onClick: () => void; badge?: number }) { return <button className={`tab-button ${active ? 'active' : ''}`} onClick={onClick}>{icon}<span>{label}</span>{badge !== undefined && <b>{badge}</b>}</button> }
function KpiStrip({ metrics }: { metrics: { failed: number; recovered: number; amount: number } }) { return <div className="kpi-strip"><Kpi icon={<TriangleAlert size={17} />} label="Failed payments" value={metrics.failed.toString()} detail="Last 30 days" tone="red" /><Kpi icon={<Check size={17} />} label="Payments recovered" value={metrics.recovered.toString()} detail={metrics.recovered ? 'Keep the momentum' : 'No recoveries yet'} tone="green" /><Kpi icon={<BarChart3 size={17} />} label="Amount recovered" value={money(metrics.amount)} detail="Net recovered value" tone="blue" /></div> }
function Kpi({ icon, label, value, detail, tone }: { icon: React.ReactNode; label: string; value: string; detail: string; tone: string }) { return <div className="kpi"><div className={`kpi-icon ${tone}`}>{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></div> }
function Overview({ scenarios: items, onRun, activeScenario, history }: { scenarios: Scenario[]; onRun: (scenario: Scenario) => void; activeScenario: string | null; history: Recovery[] }) { return <><div className="section-intro"><div><h3>Payments needing attention</h3><p>Simulate a Razorpay failure event and let the recovery agent choose one best intervention.</p></div><span className="scenario-count"><span className="status-dot" /> {items.length} scenarios ready</span></div><div className="payment-grid">{items.map((scenario) => <PaymentCard key={scenario.id} scenario={scenario} onRun={onRun} running={activeScenario === scenario.id} completed={history.some((item) => item.customer?.email === scenario.email)} />)}</div><div className="policy-banner"><div className="policy-icon"><ShieldCheck size={20} /></div><div><b>Every action is policy-led</b><p>The agent weighs recovery probability, customer value, and intervention cost before it acts.</p></div><ArrowUpRight size={17} /></div></> }
function PaymentCard({ scenario, onRun, running, completed }: { scenario: Scenario; onRun: (scenario: Scenario) => void; running: boolean; completed: boolean }) { return <article className="payment-card"><div className="card-top"><div className={`customer-avatar ${scenario.tone}`}>{scenario.initials}</div><div className="customer-info"><b>{scenario.customer}</b><span>{scenario.email}</span></div><button className="icon-button" aria-label="More payment details"><MoreHorizontal size={18} /></button></div><div className="amount-row"><div><span>Amount due</span><strong>{money(scenario.amount)}</strong></div><span className={`failure-chip ${scenario.tone}`}><span className="chip-dot" /> {scenario.failedType.replace('_', ' ')}</span></div><div className="card-details"><Detail icon={<CreditCard size={14} />} label="Payment ID" value={`pay_${scenario.id.slice(-2)}8f2a`} /><Detail icon={<Zap size={14} />} label="Event ID" value={scenario.id} /><Detail icon={<Clock3 size={14} />} label="Attempt" value={`#${scenario.retry}`} /></div><p className="scenario-description">{scenario.description}</p><div className="card-footer"><span className={completed ? 'completed-label' : ''}>{completed ? <><Check size={14} /> Agent action complete</> : <><span className="status-dot pending" /> Awaiting action</>}</span><button className="action-button" onClick={() => onRun(scenario)} disabled={running}>{running ? <><LoaderCircle size={15} className="spin" /> Thinking</> : completed ? <>Run again <RefreshCw size={14} /></> : <>Agent to action <ArrowRight size={14} /></>}</button></div></article> }
function Detail({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="detail"><span>{icon} {label}</span><b>{value}</b></div> }
function Execution({ executions }: { executions: Recovery[] }) { if (!executions.length) return <EmptyState icon={<Zap size={24} />} title="No active executions" copy="Run the agent on a live payment scenario to see its decisions and actions here." />; return <div className="execution-list">{executions.map((item) => <article className="execution-card" key={item.event_id}><div className="execution-head"><div className="execution-title"><div className="execution-icon"><Zap size={16} /></div><div><b>{item.chosen_action?.replaceAll('_', ' ')}</b><span>{item.customer?.name || 'Customer'} · {timeAgo(item.timestamp)}</span></div></div><span className="status-tag success"><Check size={13} /> Completed</span></div><div className="execution-body"><div className="execution-metric"><span>Payment</span><b>{money(item.amount_due)}</b><small>{item.failed_type?.replace('_', ' ')}</small></div><div className="execution-metric"><span>Recovery score</span><b>{item.recovery_score}/100</b><small>Baseline {Math.round((item.baseline_probability || 0) * 100)}%</small></div><div className="reasoning"><span><MessageSquareText size={14} /> Agent reasoning</span><p>{item.agent_reasoning || 'Action selected from policy.'}</p></div></div>{item.rescue_link_url && <div className="link-result"><span><LockKeyhole size={14} /> Rescue link generated</span><a href={item.rescue_link_url} target="_blank" rel="noreferrer">{item.rescue_link_url} <ArrowUpRight size={13} /></a></div>}{item.retry_delay_hours && <div className="link-result retry-result"><span><TimerReset size={14} /> Retry scheduled</span><b>In {item.retry_delay_hours} hours</b></div>}</article>)}</div> }
function HistoryView({ history, loading }: { history: Recovery[]; loading: boolean }) { if (loading) return <div className="loading-state"><LoaderCircle className="spin" size={20} /> Loading recovery history</div>; if (!history.length) return <EmptyState icon={<HistoryIcon size={24} />} title="History is clear" copy="Completed and pending agent interventions will appear here." />; return <div className="history-panel"><div className="table-head"><span>Customer & payment</span><span>Failure</span><span>Agent action</span><span>Status</span><span>Amount</span></div>{history.map((item) => <div className="history-row" key={`${item.event_id}-${item.timestamp}`}><div className="history-customer"><div className="tiny-avatar">{(item.customer?.name || 'CU').slice(0, 2).toUpperCase()}</div><div><b>{item.customer?.name || 'Unknown customer'}</b><span>{item.payment_id} · {timeAgo(item.timestamp)}</span></div></div><span className="muted-cell">{item.failed_type?.replace('_', ' ')}</span><span className="action-cell">{item.chosen_action?.replaceAll('_', ' ')}</span><span><span className={`status-tag ${item.status === 'RECOVERED' ? 'success' : 'pending-tag'}`}>{item.status === 'RECOVERED' ? <Check size={12} /> : <Clock3 size={12} />} {item.status || 'Pending'}</span></span><b className="amount-cell">{money(item.amount_due)}</b></div>)}</div> }
function EmptyState({ icon, title, copy }: { icon: React.ReactNode; title: string; copy: string }) { return <div className="empty-state"><div className="empty-icon">{icon}</div><h3>{title}</h3><p>{copy}</p></div> }
export default App
